In [1]:
import malariagen_data

/opt/homebrew/Caskroom/miniconda/base/envs/malariagen/lib/python3.11/site-packages/requests/__init__.py:92: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

In [2]:
ag3 = malariagen_data.Ag3(
    "simplecache::gs://vo_agam_release_master_us_central1",
    simplecache=dict(cache_storage="../gcs_cache"),
    results_cache="results_cache",
)
ag3

<MalariaGEN Ag3 API client>
Storage URL                           : simplecache::gs://vo_agam_release_master_us_central1
Data releases available               : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14, 3.15, 3.16
Results cache                         : /Users/katie.barr/malariagen-data-python/notebooks/results_cache
Cohorts analysis                      : 20260120
AIM analysis                          : 20220528
Site filters analysis                 : dt_20200416
Software version                      : malariagen_data 15.8.0.post13+b769b728
Client location                       : England, United Kingdom
Data filtered to unrestricted use only: False
Data filtered to surveillance use only: False
Relevant data releases                : 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3.13, 3.14, 3.15, 3.16
---
Please note that data are subject to terms of use,
for more information see the Vector Observatory website https://www.malariagen.net/vobs/
or contact support@malariagen.net. For API documentation see
https://malariagen.github.io/malariagen-data-python/v15.8.0.post13+b769b728/Ag3.html

In [3]:
!rm -rf results_cache

In [4]:
df_stats = ag3.diversity_stats(
    sample_sets="AG1000G-TZ",
    cohorts="admin2_year",
    cohort_size=10,
    region="3L:15,000,000-16,000,000",
    site_mask="gamb_colu_arab",
    site_class="CDS_DEG_4",
)
df_stats

Access SNP calls: ⠹ (0:00:00.17)

/Users/katie.barr/malariagen-data-python/malariagen_data/anopheles.py:542: UserWarning: Cohort (TZ-05_Muleba_pwan_2015) has insufficient samples (1) for requested cohort size (10), dropping.
  cohort_queries = self._setup_cohort_queries(
/Users/katie.barr/malariagen-data-python/malariagen_data/anopheles.py:542: UserWarning: Cohort (TZ-25_Muheza_arab_2013) has insufficient samples (1) for requested cohort size (10), dropping.
  cohort_queries = self._setup_cohort_queries(

Access SNP calls: ⠏ (0:00:03.01)

I0918 15:27:53.879395 13481264 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0918 15:27:53.895232 13481389 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(119, generation: 1)

Access SNP calls: ⠦ (0:00:06.14)

Locate CDS_DEG_4 sites:   0%|          | 0/10 [00:00<?, ?it/s]

/Users/katie.barr/malariagen-data-python/malariagen_data/anoph/snp_data.py:1185: UserWarning: Cohort downsampled from 137 to 10 samples. Set max_cohort_size=None to disable downsampling.
  return self._snp_calls(

Compute SNP allele counts:   0%|          | 0/68 [00:00<?, ?it/s]

/Users/katie.barr/malariagen-data-python/malariagen_data/anoph/snp_data.py:1185: UserWarning: Cohort downsampled from 32 to 10 samples. Set max_cohort_size=None to disable downsampling.
  return self._snp_calls(

Compute SNP allele counts:   0%|          | 0/49 [00:00<?, ?it/s]

/Users/katie.barr/malariagen-data-python/malariagen_data/anoph/snp_data.py:1185: UserWarning: Cohort downsampled from 47 to 10 samples. Set max_cohort_size=None to disable downsampling.
  return self._snp_calls(

Compute SNP allele counts:   0%|          | 0/37 [00:00<?, ?it/s]

/Users/katie.barr/malariagen-data-python/malariagen_data/anoph/snp_data.py:1185: UserWarning: Cohort downsampled from 32 to 10 samples. Set max_cohort_size=None to disable downsampling.
  return self._snp_calls(

Compute SNP allele counts:   0%|          | 0/24 [00:00<?, ?it/s]

Compute SNP allele counts:   0%|          | 0/23 [00:00<?, ?it/s]

/Users/katie.barr/malariagen-data-python/malariagen_data/anoph/snp_data.py:1185: UserWarning: Cohort downsampled from 40 to 10 samples. Set max_cohort_size=None to disable downsampling.
  return self._snp_calls(

Compute SNP allele counts:   0%|          | 0/49 [00:00<?, ?it/s]

,cohort,theta_pi,theta_pi_estimate,theta_pi_bias,theta_pi_std_err,theta_pi_ci_err,theta_pi_ci_low,theta_pi_ci_upp,theta_w,theta_w_estimate,...,tajima_d_ci_upp,taxon,year,month,country,admin1_iso,admin1_name,admin2_name,longitude,latitude
0,TZ-05_Muleba_arab_2015,0.014197,0.014378,-0.000181,0.001102,0.004320,0.012218,0.016539,0.016900,0.017020,...,-0.374180,arabiensis,2015,"[3, 4, 6]",Tanzania,TZ-05,Kagera,Muleba,31.651,-1.962
1,TZ-05_Muleba_gamb_2015,0.024436,0.024996,-0.000560,0.001269,0.004976,0.022508,0.027484,0.032496,0.033124,...,-0.860886,gambiae,2015,"[3, 6]",Tanzania,TZ-05,Kagera,Muleba,31.651,-1.962
2,TZ-13_Tarime_arab_2012,0.013520,0.013718,-0.000198,0.001041,0.004080,0.011678,0.015758,0.016465,0.016679,...,-0.475217,arabiensis,2012,8,Tanzania,TZ-13,Mara,Tarime,34.199,-1.431
3,TZ-25_Muheza_gamb_2013,0.020933,0.021433,-0.000500,0.001299,0.005090,0.018888,0.023979,0.020976,0.021406,...,0.217142,gambiae,2013,1,Tanzania,TZ-25,Tanga,Muheza,38.948,-4.940
4,TZ-25_Muheza_pwan_2013,0.018566,0.018947,-0.000381,0.001291,0.005062,0.016416,0.021478,0.016629,0.016902,...,0.760295,pwani,2013,1,Tanzania,TZ-25,Tanga,Muheza,38.948,-4.940
5,TZ-26_Moshi_arab_2012,0.014197,0.014429,-0.000232,0.001168,0.004580,0.012139,0.016719,0.016792,0.016908,...,-0.346878,arabiensis,2012,8,Tanzania,TZ-26,Manyara,Moshi,37.308,-3.482

In [5]:
df_stats = ag3.diversity_stats(
    sample_sets="AG1000G-TZ",
    cohorts="admin2_year",
    cohort_size=10,
    region="3L:15,000,000-16,000,000",
    site_mask="gamb_colu_arab",
    site_class="CDS_DEG_4",
)
df_stats

/Users/katie.barr/malariagen-data-python/malariagen_data/anopheles.py:542: UserWarning: Cohort (TZ-05_Muleba_pwan_2015) has insufficient samples (1) for requested cohort size (10), dropping.
  cohort_queries = self._setup_cohort_queries(
/Users/katie.barr/malariagen-data-python/malariagen_data/anopheles.py:542: UserWarning: Cohort (TZ-25_Muheza_arab_2013) has insufficient samples (1) for requested cohort size (10), dropping.
  cohort_queries = self._setup_cohort_queries(

,cohort,tajima_d,tajima_d_bias,tajima_d_ci_err,tajima_d_ci_low,tajima_d_ci_upp,tajima_d_estimate,tajima_d_std_err,theta_pi,theta_pi_bias,...,theta_w_std_err,taxon,year,month,country,admin1_iso,admin1_name,admin2_name,longitude,latitude
0,TZ-05_Muleba_arab_2015,-0.666652,-0.016208,0.552529,-0.926709,-0.374180,-0.650444,0.140954,0.014197,-0.000181,...,0.001048,arabiensis,2015,"[3, 4, 6]",Tanzania,TZ-05,Kagera,Muleba,31.651,-1.962
1,TZ-05_Muleba_gamb_2015,-1.037411,-0.007611,0.337828,-1.198714,-0.860886,-1.029800,0.086182,0.024436,-0.000560,...,0.001428,gambiae,2015,"[3, 6]",Tanzania,TZ-05,Kagera,Muleba,31.651,-1.962
2,TZ-13_Tarime_arab_2012,-0.745654,-0.002122,0.536631,-1.011848,-0.475217,-0.743532,0.136898,0.013520,-0.000198,...,0.000968,arabiensis,2012,8,Tanzania,TZ-13,Mara,Tarime,34.199,-1.431
3,TZ-25_Muheza_gamb_2013,-0.008435,-0.014445,0.422265,-0.205123,0.217142,0.006010,0.107723,0.020933,-0.000500,...,0.001145,gambiae,2013,1,Tanzania,TZ-25,Tanga,Muheza,38.948,-4.940
4,TZ-25_Muheza_pwan_2013,0.485523,-0.022000,0.505545,0.254751,0.760295,0.507523,0.128968,0.018566,-0.000381,...,0.001084,pwani,2013,1,Tanzania,TZ-25,Tanga,Muheza,38.948,-4.940
5,TZ-26_Moshi_arab_2012,-0.643957,-0.030745,0.532669,-0.879547,-0.346878,-0.613213,0.135887,0.014197,-0.000232,...,0.001081,arabiensis,2012,8,Tanzania,TZ-26,Manyara,Moshi,37.308,-3.482

In [6]:
ag3.plot_diversity_stats(df_stats)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [ ]:
ag3.plot_diversity_stats(df_stats, color="taxon")

In [ ]:
figs = ag3.plot_diversity_stats(df_stats, color="admin2_name", show=False)

In [ ]:
figs[0]

In [ ]:
figs[1]

In [ ]:
figs[2]

In [ ]:
figs[3]